data:
  root: data/GoPro_sampled
  crop_size: 256
  crops_per_image: 3
  use_sampled_data: True

model:
  clip_backbone: RN50
  clip_channels:
    layer1: 256
    layer2: 512
    layer3: 1024
    layer4: 2048    
  unfreeze_layer4: False
  use_vgg_loss: False
  reset_clip_parameters: False

training:
  batch_size: 16
  lr: 1e-4
  epochs: 25
  device: cuda
  save_interval: 5
  log_dir: runs/clip_deblur
  early_stopping_patience: 5
